name: Release

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
      - "release.yml"
      - "dependabot.yml"

permissions:
  contents: write

jobs:
  release-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Bump version
        run: |
          git pull --no-commit
          VERSION=$(node -p "require('./package.json').version")
          git tag -m "v$VERSION" "v$VERSION"
          npm --no-git-tag-version version patch --verbose
          git add package.json
          UPDATED_VERSION=$(node -p "require('./package.json').version")
          git commit -m "[skip ci] Updating version to $UPDATED_VERSION"
          git push --tags
          git push
        shell: bash
