name: Release and Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
      - "release.yml"
      - "deploy.yaml"
      - "dependabot.yml"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<\>"

      - name: Bump version
        run: |
          git pull --no-commit
          VERSION=$(node -p "require('./package.json').version")
          git tag -m "v$VERSION" "v$VERSION"
          npm --no-git-tag-version version patch --verbose
          git add package.json
          UPDATED_VERSION=$(node -p "require('./package.json').version")
          git commit -m "[skip ci] Updating version to $UPDATED_VERSION"
          git push --tags
          git push
        shell: bash

  deploy:
    needs: release
    runs-on: ubuntu-latest
    if: ${{ success() }}
    permissions:
      contents: read
      pages: write
      id-token: write
      actions: write
    environment:
      name: github-pages
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v3
        with:
          path: .
          node-version: 20
          package-manager: pnpm@latest
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4